<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>RegressionAnalysis</AssemblyName>
    <RootNamespace>RegressionAnalysis</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\HousingAnalysisSource\HousingAnalysisSource.csproj" />
    <ProjectReference Include="..\SalesAnalysisSource\SalesAnalysisSource.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.Development.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>